### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by silv3r4u** [Jabes-Enock/the-best-quiz#1]
All databases migration are empty. Could you provide the sql dump, if you want, of course.

**Comment by kernel-Jarvis** [comment]
The dashboard and quiz features do not have a table, so they do not require migrations.

They are there because when I create controller and model resources I run the command < php spark make:scaffold > which creates controller, model and migrations automatically.

I ended up not documenting this. Sorry.

The project is working ok even with empty migrations in the dashboard and quiz resources.
